### ISSUE TITLE
Installation structure

### ISSUE THREAD

**Issue by dorasprime** [BugraEryilmaz/BoTorch-optim#1]
Botorch ile bu github reposu üzerinde bulunan örnek kodların başka bilgisayarlarda da çalışması için Readme.md dosyasına bir adet kurulum dosyası ekleyebilirsen çok hoş olur. Böylelikle yaptığın çalışmaları ben de bir yandan kendi bilgisayarımda deneyebilirim.

**Comment by BugraEryilmaz** [comment]
Şimdilik aklımda kaldığı kadarıyla readme dosyası oluşturdum. Eksik olup olmadığını deneyemiyorum maalesef. Dener denemez update edeceğim.

**Comment by dorasprime** [comment]
Çalıştırmak için örnek bir durum için bir kod hazırlayabilirsen senin için test edebilirim.

**Comment by dorasprime** [comment]
Running optimization batch 1/20...
Running optimization batch 2/20...
Running optimization batch 3/20...
Running optimization batch 4/20...
Running optimization batch 5/20...
Running optimization batch 6/20...
Running optimization batch 7/20...
Running optimization batch 8/20...
Running optimization batch 9/20...
Running optimization batch 10/20...
Running optimization batch 11/20...
Running optimization batch 12/20...
Running optimization batch 13/20...
Running optimization batch 14/20...
Running optimization batch 15/20...
Running optimization batch 16/20...
Running optimization batch 17/20...
Running optimization batch 18/20...
Running optimization batch 19/20...
Running optimization batch 20/20...
Done!
{'x1': 9.414160290290102, 'x2': 2.621994548824227} 0.4227447026320858


Böyle bir sonuç aldım "{'x1': 9.414160290290102, 'x2': 2.621994548824227} 0.4227447026320858" Bu çıktıyı örnek çıktı olarak da koyabilirsin Readme.md nin içine seninle aynı sonucu alıp almadığını insanlar tam olarak test etmiş olur. Yada değer olarak sen farklı bir şey alıyorsan onu koy olmadı. 

Bir de botorch-test dosyasını botorch-test.py olarak kaydedebilirsen hoç olur. 

Bunların dışında bence örnek kod sorunsuz çalışıyor gibi verdiğin installation bilgisi ile.
