### ISSUE TITLE
botorch_datcom.py test

### ISSUE THREAD

**Issue by dorasprime** [BugraEryilmaz/BoTorch-optim#4]
Algoritmanın içerisinde numpy , pytorch ve random gibi kütüphanelerin "seed" değerlerini sabit tutman gerekebilir. Örnek çıktı olarak verdiğin değere çok yakın bir değer elde etmem gerekiyor. Benim elde ettiğim değer aşağıdaki gibi: 

{'CHORD1_1': 0.4,
 'CHORD1_2': 0.01830657323679324,
 'CHORD2_1': 0.4,
 'CHORD2_2': 0.24145375085606716,
 'SSPAN1_2': 0.26067472906789535,
 'SSPAN2_2': 0.3,
 'XLE1': 1.25,
 'XLE2': 3.137126659878235}
Best CL/CD: 3.034

**Comment by BugraEryilmaz** [comment]
Evet random initialization vs yüzünden genelde 3 ile 3.15 arasında değerler üretiyor. Bu seed konusunda her kütüphanenin seed değerini ayrı ayrı initialize etmem gerekli mi yoksa sadece random kütüphanesi yeterli mi?

**Comment by BugraEryilmaz** [comment]
Tamamdır deneyerek random, numpy ve torch'un seed'lerini ayarlamanın yeterli olduğunu gördüm o şekilde update edeceğim.
